# See https://raw.githubusercontent.com/commercialhaskell/stack/stable/doc/travis-simple.yml.

# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language, because we will provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

# Ensure necessary system libraries are present.
addons:
  apt:
    packages:
      - libgmp-dev

before_install:
# Download and unpack the stack executable.
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
# Build dependencies.
- stack --no-terminal --install-ghc test --only-dependencies

script:
# Build the package, its tests, and its docs, and run the tests.
- ./scripts/build.sh
- stack --no-terminal test --haddock --no-haddock-deps
